server.port: 8080

spring.application.name: gateway

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-store-password: password
  key-alias: localhost



spring.cloud.gateway.routes:

- id: core
  uri: http://localhost:8081
  predicates:
  - Path=/core/**

